title: Cloud Dna Blog
description: Cloud Dna blog for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate

permalink: /:title.html

source: githubpages
paginate: 8
paginate_path: /blog/page:num
include:
- _redirects



plugins:
- jekyll-paginate
- jekyll-redirect-from
